//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icebreaker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IcebreakerEntities1 : DbContext
    {
        public IcebreakerEntities1()
            : base("name=IcebreakerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Log> Logs { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<LostProperty> LostProperties { get; set; }
        public DbSet<Publisher> Publishers { get; set; }
        public DbSet<PublishLog> PublishLogs { get; set; }
        public DbSet<ReceiveLog> ReceiveLogs { get; set; }
        public DbSet<Receiver> Receivers { get; set; }
        public DbSet<ScoreView> ScoreViews { get; set; }
    }
}
